Accessibility M1: Fix luminosity contrast issues
Azure/BatchExplorer pull request #2236
Opened 2020-12-15 21:39 UTC by cRui861

Fix color contrast ratio issue for 'Low Priority' on graphs for Batch accounts https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/434:
![image](https://user-images.githubusercontent.com/16728220/102275775-c131ef80-3eda-11eb-91c4-b5e359ec4e1b.png)

Fix color contrast ratio issue for account naming suffix when creating a new Batch account https://azurebatch.visualstudio.com/BatchExplorer/_workitems/edit/437:
![image](https://user-images.githubusercontent.com/16728220/102275855-e0308180-3eda-11eb-941a-b92cbaadcf5b.png)

2020-12-16 12:36 UTC, dpwatrous commented
Looks good to me, let's just clean up the commit messages a bit and tag them with their ADO work item IDs (ie: "Fixes AB#1234)

2020-12-16 12:37 UTC, dpwatrous requested changes
(See my comment above)

2020-12-16 20:34 UTC, dpwatrous approved these changes

2020-12-16 20:53 UTC, merged

2021-01-15 00:31 UTC, cRui861 commented
Fixed #2253