October a11y bug fixes
Azure/BatchExplorer pull request #2398
Opened 2021-11-11 00:55 UTC by cRui861

2021-11-11 14:36 UTC, dpwatrous commented
Looks good to me! Just a couple of minor suggestions as far as the actual Git commits are concerned:

- Let's rebase this on master so we can use the 'create a merge commit' merge option and preserve individual commits for different a11y fixes (if we don't rebase we'll have 2 merge commits, which is going to look pretty confusing in Git history)

- Since the DevOps work items aren't visible from GitHub, let's reword the commit messages with a brief description of each fix. You can still link the DevOps work item in the commit's description field. See my commit in this PR for an example.

2021-11-11 14:39 UTC, dpwatrous requested changes
(See my comment above)

2021-11-11 17:54 UTC, cRui861 commented
> Looks good to me! Just a couple of minor suggestions as far as the actual Git commits are concerned:
> 
> * Let's rebase this on master so we can use the 'create a merge commit' merge option and preserve individual commits for different a11y fixes. If we don't rebase we'll have 2 merge commits, which is going to look pretty confusing in Git history.
> * Since the DevOps work items aren't visible from GitHub, let's reword the commit messages with a brief description of each fix. You can still link the DevOps work item in the commit's description field. See my commit in this PR for an example.

Sounds good. I'll make the updates to the commit messages.

2021-11-22 19:00 UTC, gingi approved these changes
Looks good. Just 3 suggestions for localization.

2021-11-30 06:56 UTC, cRui861 commented on src/@batch-flask/ui/buttons/refresh-btn/refresh-btn.component.ts
> +    @Input() public title: string = "Refresh";
Could you point me to an example of what you mean by this?

2021-11-30 06:57 UTC, cRui861 commented on src/app/components/account/details/account-summary-card/account-summary-card.html
> +        <bl-refresh-btn [refresh]="refresh" title="Refresh account summary page"></bl-refresh-btn>
Added localization for this refresh button.

2021-11-30 06:57 UTC, cRui861 commented on src/app/components/account/details/programatic-usage/programing-sample/programing-sample.html
> +                <bl-tp-cell [value]="prerequisite" role="button" attr.aria-label="Copy {{prerequisites}} to clipboard"></bl-tp-cell>
Added localization for this arial label.

2021-12-03 00:48 UTC, zfengms approved these changes

2021-12-03 00:54 UTC, merged

2022-01-31 19:50 UTC, cRui861 commented
Fixes #2415