Prepare for release 2.13.0
Azure/BatchExplorer pull request #2482
Opened 2022-03-17 00:13 UTC by cRui861

fix #2463

2022-03-17 11:37 UTC, dpwatrous submitted a review, later dismissed

2022-03-17 19:04 UTC, gingi requested changes

2022-03-17 19:04 UTC, gingi commented on CHANGELOG.md
> +* Bring back VM SKU API support for displaying VM information in Pools [\#2462](https://github.com/Azure/BatchExplorer/issues/2462)
Maybe better:

> Restores SKU API support for displaying VM information in pools

2022-03-17 19:04 UTC, gingi commented on CHANGELOG.md
> +* Fix node heatmap display issue for taskSlots [\#2461](https://github.com/Azure/BatchExplorer/issues/2461)
Better:

> Heatmaps did not display task slot information correctly

2022-03-18 14:14 UTC, gingi approved these changes

2022-03-18 16:47 UTC, merged