Fix multiple accessibility bugs.
Azure/BatchExplorer pull request #2619
Opened 2023-01-13 13:43 UTC by wanghoppe

2023-01-13 14:03 UTC, gingi requested changes
Great work here. Requesting two general changes, which are fairly minor:

1. If an element only contains child elements with `aria-hidden="true"`, then the attribute should be set on that element.
2. Labels should be localized because they are announced by assistive technologies (as opposed to roles, which are in English).

2023-01-20 16:18 UTC, gingi approved these changes

2023-01-28 04:35 UTC, gingi approved these changes

2023-01-28 04:35 UTC, merged

2023-02-01 17:52 UTC, cRui861 commented
Fixes #2634