DataGrid: load more and virtual scrolling
Azure/BatchExplorer pull request #2799
Opened 2023-09-11 06:58 UTC by wanghoppe

2023-09-12 00:24 UTC, wanghoppe commented
AB#25124895

2023-09-12 15:07 UTC, dpwatrous requested changes
This is looking really good - I love the tests and demos you added. Let's follow up tomorrow and talk more about the overall design.

Random thought: this seems like a really good use case for some automated performance tests. I'd love to be able to track the performance of the data grid in various scenarios over time. We already have a few tests in Playwright which run a real Electron process. Seems like that might be a good place to put perf tests.

2023-09-12 15:07 UTC, dpwatrous commented on packages/playground/src/demo/display/task-grid/task-data-grid.tsx
> +    const [isCompat, setIsCompat] = React.useState<boolean>(false);
Typo: Compat -> Compact

2023-09-12 15:07 UTC, dpwatrous commented on packages/playground/src/demo/display/task-grid/task-data-grid.tsx
> +                        label="Compat Mode"
Typo: Compat -> Compact

2023-09-12 15:12 UTC, dpwatrous commented
Looks like there's a styling issue with errors on the demo page (this definitely wouldn't pass color contrast requirements):

 
<img width="506" alt="Screenshot 2023-09-12 at 11 08 59 AM" src="https://github.com/Azure/BatchExplorer/assets/509299/2eed6528-bea0-424b-aff7-7783b90e182a">

2023-09-13 03:18 UTC, wanghoppe commented on packages/bonito-ui/src/components/data-grid/data-grid.tsx
> +    hasMore?: boolean;
Agreed, one questions is that `hasMore` actually used as a loading indicator for initial load as well. `hasMore = true` while `items` are empty would indicate that it's initial loading, later when the `items` are populated and set `hasMore = false` meaning the initial load is finished. I am thinking whether we should have separate filed `isLoading` to do this.

2023-09-13 14:27 UTC, dpwatrous commented on packages/bonito-ui/src/components/data-grid/data-grid.tsx
> +    hasMore?: boolean;
After some discussion, I'm fine if we leave this as-is for now.

2023-09-15 08:25 UTC, wanghoppe commented
> Looks like there's a styling issue with errors on the demo page (this definitely wouldn't pass color contrast requirements):
> 
> <img alt="Screenshot 2023-09-12 at 11 08 59 AM" width="506" src="https://user-images.githubusercontent.com/509299/267377187-2eed6528-bea0-424b-aff7-7783b90e182a.png">

I use the latest @fluentui/azure-themes instead, still need to make some adjustment to make the error message bar looked OK.  Also adjust some style to make the shimmering more promient on dark and light theme.
![image](https://github.com/Azure/BatchExplorer/assets/28680231/cbd82886-aa00-4001-b573-e8d8e87fee28)

2023-09-21 15:49 UTC, dpwatrous requested changes

2023-09-21 15:49 UTC, dpwatrous commented on packages/bonito-ui/package.json
> +    "watch": "npm run compile:esm -- --watch --preserveWatchOutput",
This looks like it got reverted somehow

2023-09-21 15:49 UTC, dpwatrous commented on web/dev-server/resources/i18n/resources.en.json
> +{
This file shouldn't be checked in (it's in .gitignore)

2023-10-17 00:36 UTC, dpwatrous approved these changes

2023-10-17 00:37 UTC, merged